version: 2
jobs:
  release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Run goreleaser
          command: curl -sL https://git.io/goreleaser | bash
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Pull Dependencies
          command: go mod download
      - run:
          name: Build binary
          command: make

workflows:
  version: 2
  commit:
    jobs:
      - build
  build:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /^[0-9]+(\.[0-9]+)*/
  build_on_tag:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+(\.[0-9]+)*/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+(\.[0-9]+)*/
