on: release
name: Build
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
          platforms: 'linux/amd64, darwin/amd64, windows/amd64'
          package: 'netlify-cms-oauth-provider-go'
          name: 'netlify-cms-oauth-provider-go'
          compress: 'false'
          dest: 'dist'